### ISSUE TITLE
stop execution asap if you see invalid user token

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/python-agent-robot#4]
```
[ ERROR ] Taking listener 'robotframework_zebrunner.ZebrunnerListener' into use failed: Importing listener 'robotframework_zebrunner.ZebrunnerListener' failed: Creating instance failed: AgentApiError: ('Failed to authorize zebrunner agent', {'status_code': 403, 'body': {'requestId': 'e5a032b026030482', 'code': 'IAM-3600', 'message': 'User is not active'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/robotframework_zebrunner/listener.py", line 36, in __init__
    self.api.auth()
  File "/usr/local/lib/python3.8/site-packages/robotframework_zebrunner/api/client.py", line 82, in auth
    raise AgentApiError(
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
/usr/local/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (None)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(

```

**Comment by azarouski** [comment]
Program interruption if authentication fails was added.

[Release on PyPi](https://pypi.org/project/robotframework-zebrunner/0.3.1/)

To use in your project just install dependency:
<details>
  <summary>with Pip</summary>

  ```
pip install robotframework-zebrunner==0.3.1
  ```
</details>

<details>
  <summary>or with Poetry</summary>

  ```
  poetry add robotframework-zebrunner==0.3.1
  ```
</details>

**Comment by vdelendik** [comment]
we've found that not latest sources were used for 0.3.1 version so removed from pypi... let's merge and build again

**Comment by vdelendik** [comment]
0.3.2 released with latest sources and this fix

**Comment by ghost** [comment]
verified, fixed.
